steps:
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - init
  - -input=false
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - validate
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - plan
  - -input=false
  - -out=tfplan
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - apply
  - -auto-approve
  - -input=false
  - tfplan